spring:
  application:
    name: springCloudGateway
  cloud:
    gateway:
      routes:
        - id: ms1
          uri: http://localhost:8081
          predicates:
            - Path=/ms1/**
          filters:
            - name: L1Filter
              args:
                pre: true
                post: true
        - id: ms2
          uri: http://localhost:8082
          predicates:
            - Path=/ms2/**
        - id: ms3
          uri: http://localhost:8083
          predicates:
            - Path=/ms3/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true
