server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: ms1
          uri: lb://MS1
          predicates:
            - Path=/ms1/**
        - id: ms2
          uri: lb://ms2
          predicates:
            - Path=/ms2/**

eureka:
  client:
    register-with-eureka: true # 유레카 서버에 등록할지 여부
    fetch-registry: true # 유레카 서버의 정보를 가져올지 여부
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka #유레카 서버 주소